Creature.create({name: "Luke", description: "Jedi"})
Creature.create({name: "Darth Vader", description: "Father of Luke"})
Creature.create({name: "Kylo Ren", description: "Emo Jedi"})
Creature.create({name: "Count Duku", description: "Limp saber"})
Creature.create({name: "Jaba the Hut", description: "Fat guy"})
