Creature.create({name: "Yoda", description: "Jedi Master"})
Creature.create({name: "Bobafat", description: "Bounty Hunter"})
Creature.create({name: "General Grievous", description: "Dual Sword"})
Creature.create({name: "General Palpatine", description: "Darth Sideous"})
Creature.create({name: "General Hux", description: "Robot Lover"})
Creature.create({name: "Luke", description: "Jedi"})
